In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

In [2]:
tau_data = Path("__file__").resolve().parents[1] / 'data' / 'UCBERKELEYAV1451_04_26_22.csv'

In [4]:
# load baseline data
df = pd.read_csv(tau_data, index_col=0, header=0)

In [10]:
df.head()

,VISCODE,VISCODE2,EXAMDATE,INFERIORCEREBELLUM_SUVR,INFERIORCEREBELLUM_VOLUME,ERODED_SUBCORTICALWM_SUVR,ERODED_SUBCORTICALWM_VOLUME,BRAAK1_SUVR,BRAAK1_VOLUME,BRAAK34_SUVR,...,RIGHT_PUTAMEN_VOLUME,RIGHT_THALAMUS_PROPER_SUVR,RIGHT_THALAMUS_PROPER_VOLUME,RIGHT_VENTRALDC_SUVR,RIGHT_VENTRALDC_VOLUME,RIGHT_VESSEL_SUVR,RIGHT_VESSEL_VOLUME,WM_HYPOINTENSITIES_SUVR,WM_HYPOINTENSITIES_VOLUME,update_stamp
RID,,,,,,,,,,,,,,,,,,,,,
21,init,m144,2018-02-02,1.0285,55285,1.1771,110695,1.1937,2869,1.2152,...,4169,1.5224,5874,1.3860,3378,1.4576,10.0,1.0615,2460,2022-04-27 15:31:20.0
31,init,m150,2018-04-24,0.9647,62344,1.0258,55683,1.2463,2558,1.0969,...,5766,1.1421,6016,1.2340,3178,1.3691,2.0,0.7641,26845,2022-04-27 15:31:20.0
31,y1,m162,2019-04-23,0.9636,61510,1.0193,50427,1.2264,2508,1.0675,...,5537,1.0801,5865,1.1644,3060,1.4203,15.0,0.7805,28306,2022-04-27 15:31:20.0
56,init,m144,2018-02-20,0.9790,64415,1.2442,114401,1.2682,3809,1.2016,...,4026,1.3396,6601,1.3625,3655,1.6190,42.0,1.0556,1385,2022-04-27 15:31:20.0
56,y1,m156,2019-01-10,0.9548,63302,1.2863,118625,1.1931,3666,1.1839,...,4145,1.3618,6349,1.3873,3625,1.4511,10.0,1.0850,1427,2022-04-27 15:31:20.0

In [20]:
result_cols = ['CTX_LH_ENTORHINAL_SUVR',
'CTX_RH_ENTORHINAL_SUVR',
'LEFT_AMYGDALA_SUVR',
'RIGHT_AMYGDALA_SUVR',
'CTX_LH_PARAHIPPOCAMPAL_SUVR',
'CTX_RH_PARAHIPPOCAMPAL_SUVR',
'CTX_LH_FUSIFORM_SUVR',
'CTX_RH_FUSIFORM_SUVR',
'CTX_LH_INFERIORTEMPORAL_SUVR',
'CTX_RH_INFERIORTEMPORAL_SUVR',
'CTX_LH_MIDDLETEMPORAL_SUVR',
'CTX_RH_MIDDLETEMPORAL_SUVR']

In [27]:
df['META_ROI'] = df[result_cols].mean(axis=1)
df.head()

,VISCODE,VISCODE2,EXAMDATE,INFERIORCEREBELLUM_SUVR,INFERIORCEREBELLUM_VOLUME,ERODED_SUBCORTICALWM_SUVR,ERODED_SUBCORTICALWM_VOLUME,BRAAK1_SUVR,BRAAK1_VOLUME,BRAAK34_SUVR,...,RIGHT_THALAMUS_PROPER_VOLUME,RIGHT_VENTRALDC_SUVR,RIGHT_VENTRALDC_VOLUME,RIGHT_VESSEL_SUVR,RIGHT_VESSEL_VOLUME,WM_HYPOINTENSITIES_SUVR,WM_HYPOINTENSITIES_VOLUME,update_stamp,meta_roi,META_ROI
RID,,,,,,,,,,,,,,,,,,,,,
21,init,m144,2018-02-02,1.0285,55285,1.1771,110695,1.1937,2869,1.2152,...,5874,1.3860,3378,1.4576,10.0,1.0615,2460,2022-04-27 15:31:20.0,1.234958,1.234958
31,init,m150,2018-04-24,0.9647,62344,1.0258,55683,1.2463,2558,1.0969,...,6016,1.2340,3178,1.3691,2.0,0.7641,26845,2022-04-27 15:31:20.0,1.145025,1.145025
31,y1,m162,2019-04-23,0.9636,61510,1.0193,50427,1.2264,2508,1.0675,...,5865,1.1644,3060,1.4203,15.0,0.7805,28306,2022-04-27 15:31:20.0,1.137825,1.137825
56,init,m144,2018-02-20,0.9790,64415,1.2442,114401,1.2682,3809,1.2016,...,6601,1.3625,3655,1.6190,42.0,1.0556,1385,2022-04-27 15:31:20.0,1.235883,1.235883
56,y1,m156,2019-01-10,0.9548,63302,1.2863,118625,1.1931,3666,1.1839,...,6349,1.3873,3625,1.4511,10.0,1.0850,1427,2022-04-27 15:31:20.0,1.208933,1.208933

In [29]:
results_df = df[['EXAMDATE','META_ROI']].copy()
results_df.head()

       EXAMDATE  META_ROI
RID
21   2018-02-02  1.234958
31   2018-04-24  1.145025
31   2019-04-23  1.137825
56   2018-02-20  1.235883
56   2019-01-10  1.208933

In [30]:
results_df.to_csv(Path("__file__").resolve().parents[1] / 'data' / 'tau_meta_roi.csv')